name: onemore
description: ONE MORE hypercasual game built with Flutter + Flame
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.13.1
  google_fonts: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: false

